name: Remove Label On Review from PR

on:
  pull_request_review:
    types: submitted
    
    

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-remove-labels@v1
#         if: ${{ startsWith(github.event.comment.body, '/remove-labels') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: on review
